/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjjogowar;

import java.awt.Color;
import javax.swing.JOptionPane;
import model.ClassOpt;
/**
 *
 * @author Glaucia
 */
public class frmOpt extends javax.swing.JFrame {
    
    /**
     * Creates new form frmOpt
     */
    int meio1;
    String name1;
    ClassOpt opt;
    frmMenu menupr;
    public frmOpt(ClassOpt opt, frmMenu menupr) {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.LIGHT_GRAY);
        this.opt = opt;
        this.menupr=menupr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        NamePlay1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Save Changes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        NamePlay1.setText("Player 1 Name");
        NamePlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamePlay1ActionPerformed(evt);
            }
        });
        getContentPane().add(NamePlay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 110, 20));
        NamePlay1.getAccessibleContext().setAccessibleName("NamePlay1");

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setText("Changelog");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(1);
        jTextArea1.setRows(1);
        jTextArea1.setText("* Version 1.0   Release  \n* Version 1.1   Add Results, fix bugs\n* Version 1.2   Add Action points system, fix bugs\n* Version 1.3   Improved AP System, fix bugs\n* Version 1.4   Add Charge atack \n* Version 1.4.1 Windows centralizad\n* Version 1.4.2 Layout Improvement,put more bugs... :c\n* Version 1.4.3 FIX BUGS!!! and now AP never be less than 0\n* Version 1.5   Add Menu, fix bug\n* Version 1.5.1 Improved Results, Improved Atack and Repair, add Hp Bar\n* Version 1.5.2 Add images on Menus, fix bugs\n* Version 1.5.3 Reduce Charge health cost, fix bugs\n* Version 1.5.4 Fix bugs menu related, improved menu");
        jTextArea1.setSelectionStart(0);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 47, 460, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/atack3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println(meio1);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        menupr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void NamePlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamePlay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamePlay1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      name1 = NamePlay1.getText();
      menupr.getOpt().setName1(name1);
        System.out.println(name1);
      JOptionPane.showMessageDialog(null, "Changes Saved");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NamePlay1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
   // private ClassOpt objOpt;

}
